import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/**/*.ts', 'src/endpoints.json'],
  format: ['esm'],
  target: 'es2020',
  outDir: 'dist',
  clean: true,
  bundle: false,
  splitting: false,
  sourcemap: false,
  dts: false,
  publicDir: false,
  onSuccess: process.platform === 'win32' ? undefined : 'chmod +x dist/index.js',
  loader: {
    '.json': 'copy',
  },
  noExternal: [],
  external: [
    '@azure/msal-node',
    '@modelcontextprotocol/sdk',
    '@toon-format/toon',
    '@zodios/core',
    'commander',
    'dotenv',
    'express',
    'express-rate-limit',
    'helmet',
    'js-yaml',
    'open',
    'winston',
    'zod',
    'zod-to-json-schema',
    'keytar',
  ],
});
